const products1 = [
    // Electronics Category
 
    {
      id:1,
      name: "Wireless Bluetooth Headphones",
      image: "https://images.pexels.com/photos/610945/pexels-photo-610945.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "High-quality Wireless Bluetooth Headphones with noise cancellation and long battery life.",
      category: "Electronics",
      price:999,
      instock: true,
      quantity: 1
    },
    {
      id:2,
      name: "Smartphone 128GB",
      image: "https://images.pexels.com/photos/28582718/pexels-photo-28582718/free-photo-of-hand-holding-smartphone-with-settings-displayed.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Latest 5G smartphone with a stunning display and powerful camera.",
      category: "Electronics",
      price:20000,
      instock: true,
      quantity: 50
    },
    {
      id:3,
      name: "4K LED Smart TV 55 inch",
      image: "https://images.pexels.com/photos/7214467/pexels-photo-7214467.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "55-inch 4K UHD Smart TV with HDR and built-in streaming apps.",
      category: "Electronics",
      price:80000,
      instock: true,
      quantity: 30
    },
    {
      id:4,
      name: "Portable Power Bank 10000mAh",
      image: "https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "High-quality Portable Power Bank 10000mAh.",
      category: "Electronics",
      price:4000,
      instock: true,
      quantity: 2
    },
    {
      id:5,
      name: "Smart Watch with GPS",
      image: "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "Fitness and activity tracking smartwatch with heart rate monitor and GPS.",
      category: "Electronics",
      price:5000,
      instock: false,
      quantity: 0
    },
    {
      id:6,
      name: "Wireless Earbuds with Charging Case",
      image: "https://images.pexels.com/photos/3921887/pexels-photo-3921887.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "High-quality wireless earbuds with noise cancellation and 20-hour battery life.",
      category: "Electronics",
      price:6000,
      instock: true,
      quantity: 150
    },
    {
      id:7,
      name: "Gaming Laptop 16GB RAM",
      image: "https://images.pexels.com/photos/792345/pexels-photo-792345.jpeg?auto=compress&cs=tinysrgb&w=600",
      description: "High-performance gaming laptop with Intel i7 processor and RTX 3060 GPU.",
      category: "Electronics",
      price:7000,
      instock: false,
      quantity: 0
    },
    {
      id:8,
      name: "Noise Cancelling Headphones",
      image: "https://images.pexels.com/photos/205926/pexels-photo-205926.jpeg?auto=compress&cs=tinysrgb&w=400",
      category: "Electronics",
      description: "Over-ear noise-cancelling headphones with wireless Bluetooth connectivity.",
      price:800,
      instock: true,
      quantity: 100,
    },
    {
      id:9,
      name: "Home Security Camera System",
      image: "https://images.pexels.com/photos/24503710/pexels-photo-24503710/free-photo-of-smart-home-security-system.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "1080p HD home security camera with night vision and motion detection.",
      category: "Electronics",
      price:50000,
      instock: true,
      quantity: 80,
    },
    {
      id:10,
      name: "Vacuum Cleaner",
      image: "https://images.pexels.com/photos/38325/vacuum-cleaner-carpet-cleaner-housework-housekeeping-38325.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Cordless vacuum cleaner with powerful suction and long battery life.",
      category: "Electronics",
      price:60000,
      instock: true,
      quantity: 40
    },
  
  
    // Fashion Category
    {
      id: 11,
      name: "T-shirt",
      image: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "100% cotton T-shirt with a comfortable fit.",
      category: "Clothing",
      price:1000,
      instock: true,
      quantity: 1,
    },
    {
    id: 12,
    name: "Jeans",
    image: "https://images.pexels.com/photos/52518/jeans-pants-blue-shop-52518.jpeg?auto=compress&cs=tinysrgb&w=400",
    description: "Slim-fit jeans with stretchable fabric.",
    category: "Clothing",
    price:200,
    instock: true,
    quantity: 80,
    },
    {
      id:13,
      name: "Leather Jacket",
      image: "https://images.pexels.com/photos/1124468/pexels-photo-1124468.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Genuine leather jacket with a vintage design and multiple pockets.",
      category: "Clothing",
      price:60000,
      instock: true,
      quantity: 50,
    },
    {
      id: 14,
      name: "Hoodie",
      image: "https://images.pexels.com/photos/1035692/pexels-photo-1035692.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Cozy hoodie with kangaroo pockets.",
      category: "Clothing",
      price:4000,
      instock: false,
      quantity: 0,
    },
    {
    id: 15,
    name: "Sweater",
    image: "https://images.pexels.com/photos/5709908/pexels-photo-5709908.jpeg?auto=compress&cs=tinysrgb&w=400",
    description: "Woolen sweater with ribbed cuffs.",
    category: "Clothing",
    price:5000,
    instock: false,
    quantity: 0,
    },
    {
      id: 16,
    name: "Skirt",
    image: "https://images.pexels.com/photos/2388245/pexels-photo-2388245.jpeg?auto=compress&cs=tinysrgb&w=400",
    description: "Pleated skirt with a side zipper.",
    category: "Clothing",
    price:6000,
    instock: false,
    quantity: 0,
    },
    {
      id:17,
      name: "Woolen Scarf",
      image: "https://images.pexels.com/photos/3091073/pexels-photo-3091073.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Soft and cozy scarf available in various colors and patterns.",
      category: "Clothing",
      price:7000,
      instock: true,
      quantity: 300,
    },
    {
      id: 18,
      name: "Shorts",
      image: "https://images.pexels.com/photos/1760078/pexels-photo-1760078.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Casual shorts with drawstring waist.",
      category: "Clothing",
      price:50000,
      instock: true,
      quantity: 60,
    },
    {
      id: 19,
    name: "Pajamas",
    image: "https://images.pexels.com/photos/364362/pexels-photo-364362.jpeg?auto=compress&cs=tinysrgb&w=400",
    description: "Comfortable cotton pajamas set.",
    category: "Clothing",
    price:60000,
    instock: true,
    quantity: 50,
    },
    {
      id:20,
      name: "Men's Formal Suit",
      image: "https://images.pexels.com/photos/28580375/pexels-photo-28580375/free-photo-of-stylish-man-in-suit-and-sunglasses-on-red-background.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Men's Formal Suit with a classic fit, available in various colors.",
      category: "Clothing",
      price:70000,
      instock: false,
      quantity: 0,
    },
  
    // Accessories Category
    {
      id:21,
      name: "Waterproof Backpack",
      image: "https://images.pexels.com/photos/20094394/pexels-photo-20094394/free-photo-of-man-wearing-backpack-by-the-shore.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Trendy backpack with multiple compartments and a durable exterior.",
      category: "Accessories",
      price:1000,
      instock: false,
      quantity: 0
    },
    {
      id:22,
      name: "Leather Wallet",
      image: "https://images.pexels.com/photos/4452635/pexels-photo-4452635.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Compact and stylish leather wallet with multiple card slots.",
      category: "Accessories",
      price:200,
      instock: true,
      quantity: 3
    },
    {
      id:23,
      name: "Stainless Steel Watch",
      image: "https://images.pexels.com/photos/128619/pexels-photo-128619.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Classic analog watch with a stainless steel band and water-resistant design.",
      category: "Accessories",
      price:70000,
      instock: true,
      quantity: 85
    },
    {
      id:24,
      name: "Sunglasses Case",
      image: "https://images.pexels.com/photos/10556653/pexels-photo-10556653.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Polarized sunglasses with UV protection and anti-glare lenses.",
      category: "Accessories",
      price:4000,
      instock: true,
      quantity: 200
    },
    {
      id:25,
      name: "Travel Neck Pillow",
      image: "https://images.pexels.com/photos/8669387/pexels-photo-8669387.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Very Stylish Travel Neck Pillow.",
      category: "Accessories",
      price:5000,
      instock: true,
      quantity: 180
    },
    {
      id:26,
      name: "Fashion Bracelet",
      image: "https://images.pexels.com/photos/28558344/pexels-photo-28558344/free-photo-of-vibrant-portrait-of-smiling-woman-with-red-hair.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Very Stylish Fashion Bracelet.",
      category: "Accessories",
      price:6000,
      instock: true,
      quantity: 250
    },
    {
      id:27,
      name: "Leather Laptop Bag",
      image: "https://images.pexels.com/photos/5090704/pexels-photo-5090704.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Compact Leather Laptop Bag.",
      category: "Accessories",
      price:7000,
      instock: true,
      quantity: 70
    },
    {
      id: 28,
      name: "Hat",
      image: "https://images.pexels.com/photos/984619/pexels-photo-984619.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Wide-brim hat made from organic cotton.",
      category: "Accessories",
      price:500,
      instock: true,
      quantity: 50,
    },
    {
      id:29,
      name: "Leather Gloves",
      image: "https://images.pexels.com/photos/3911254/pexels-photo-3911254.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Genuine leather gloves with a soft lining for comfort and warmth.",
      category: "Accessories",
      price:60000,
      instock: true,
      quantity: 110
    },
    {
      id:30,
      name: "Keychain with Carabiner",
      image: "https://images.pexels.com/photos/5474291/pexels-photo-5474291.jpeg?auto=compress&cs=tinysrgb&w=400",
      description: "Compact leather keychain holder with snap closure.",
      category: "Accessories",
      price:100,
      instock: true,
      quantity: 350
    }
  ];
  export default products1;
  